# nixos/hosts/watson/configuration.nix
# This module contains the config for a lenovo t14 w/ AMD CPU

{ config, lib, pkgs, ... }:{

  # Imports
  imports =[ 
    ./hardware-configuration.nix    # hardware config (generated by NixOS)
    ./../../common/default.nix      # default settings, programs, packages and services  
    ./../../common/graphical.nix    # common graphical packages
    ./../../modules/hyprland.nix    # hyprland desktop environment
  ];

  # DO NOT CHANGE
  system.stateVersion = "25.05";

  # Boot settings
  boot.loader = { 
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # Networking
  networking = {
    hostName = "watson";
    networkmanager.enable = true;
  };

  # Bluetooth settings
  hardware.bluetooth = {
    enable = true;        # enable Bluetooth
    powerOnBoot = false;  # don't turn bluetooth on at boot
  };

  # Host specific system packages
  environment.systemPackages = with pkgs; [];

  # Users
  users.users.kevin = {
    isNormalUser = true;
    shell = pkgs.zsh;
    description = "Kevin Liguori";
    extraGroups = [ "networkmanager" "wheel" "libvirtd" "kvm" ];
  };

}
