# nixos/hosts/watson/configuration.nix
# This module contains the config for a lenovo t14 w/ AMD CPU

{ config, lib, pkgs, ... }:{

  # Imports
  imports =[ 
    ./hardware-configuration.nix    # hardware config (generated by NixOS)
    ./../../common/default.nix      # default settings, programs, packages and services  
    ./../../common/graphical.nix    # common graphical packages
    ./../../modules/hyprland.nix    # hyprland desktop environment
    ./../../modules/neovim.nix      # neovim editor
  ];

  # DO NOT CHANGE
  system.stateVersion = "25.05";

  # Boot settings
  boot = {
    loader = { 
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    supportedFilesystems = [ "zfs" ];
    zfs.forceImportRoot = true;
    initrd.postDeviceCommands = lib.mkAfter ''
      zpool import -Nf zpool
      zfs rollback -r zpool/local/root@blank
    '';
  };

  # Symlink etc files
  systemd.tmpfiles.rules = [
    "d /persist/etc/NetworkManager/system-connections 0700 root root - -"
    "L+ /etc/NetworkManager/system-connections - - - - /persist/etc/NetworkManager/system-connections"
  ];

  # Networking
  networking = {
    hostName = "watson";
    hostId = "36306665";
    networkmanager.enable = true;
  };

  # Bluetooth settings
  hardware.bluetooth = {
    enable = true;        # enable Bluetooth
    powerOnBoot = false;  # don't turn bluetooth on at boot
  };

  # Host specific system packages
  environment.systemPackages = with pkgs; [];

  # Users
  users.users.kevin = {
    isNormalUser = true;
    hashedPassword = "$y$j9T$PtbhYydbhh.z0qInjgrQS1$0oLkk3FlJztVtmVJqpWQWCDs8kdX2zzMkJKQkkzAtu9";
    shell = pkgs.zsh;
    description = "Kevin Liguori";
    extraGroups = [ "networkmanager" "wheel" "libvirtd" "kvm" ];
  };

}
