# nixos/hosts/lestrade/configuration.nix
# This module contains the config for a Dell XPS15 w/ Nvidia GPU

{ config, lib, pkgs, ... }:{

  # Imports
  imports =[ 
    ./hardware-configuration.nix # hardware config (generated by NixOS)
    ./../common/default.nix      # default settings, programs, packages and services  
    ./../modules/hyprland.nix    # hyprland desktop environment
    ./../modules/graphical.nix   # hyprland desktop environment
  ];

  # DO NOT CHANGE
  system.stateVersion = "25.05";

  # Boot settings
  boot = {
    # extra kernel modules to include
    kernelModules = [ 
      "sg" # for recognizing blu ray player
    ]; 
    # bootloader settings
    loader = { 
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  # Networking
  networking = {
    hostName = "lestrade";
    networkmanager.enable = true;
  };

  # Bluetooth settings
  hardware.bluetooth = {
    enable = true;        # enable Bluetooth
    powerOnBoot = false;  # don't turn bluetooth on at boot
  };

  # Host specific system packages
  environment.systemPackages = with pkgs; [];

  # Users
  users.users.minimumaction = {
    isNormalUser = true;
    shell = pkgs.zsh;
    description = "Kevin Liguori";
    extraGroups = [ "networkmanager" "wheel" "libvirtd" "kvm" ];
  };

}